### ISSUE TITLE
the range of vector field 

### ISSUE THREAD

**Issue by NanYoMy** [lucasmansilla/ACRN_Chest_X-ray_IA#1]
https://github.com/lucasmansilla/ACRN_Chest_X-ray_IA/blob/0aaec6226a208d3076d7d53f5d8d1af76fb213e0/acregnet/displacement.py#L42

hi, I notice that, in your 'batch_displacement_warp2d' method, you had assumed that the range of vector field (deformation field) is ranged in [0, xlen][0, ylen].
but I review the  "VectorCNN" class, this sub-network may produce negative value. so could you please tell me why the vector field range must be [0, xlen][0, ylen] rather than [-xlen, xlen][-ylen, ylen].
thx.

**Comment by lucasmansilla** [comment]
Hi. It's a mistake I made while documenting. I've already fixed it. Thanks for pointing that out.
