### ISSUE TITLE
Which dataset is the CLI model trained on?

### ISSUE THREAD

**Issue by b1a0** [lucasmansilla/ACRN_Chest_X-ray_IA#17]
I was wondering whether you could provide information which dataset (JSRT, Montgomery or Shenzen) your CLI model is trained on and whether the training parameters were the ones published in the paper. Thanks!

**Comment by lucasmansilla** [comment]
Hi @b1a0,

The CLI model was trained on JSRT using the training parameters reported in the paper.

**Comment by b1a0** [comment]
Thank you for the clarification.
