### ISSUE TITLE
A  consultation

### ISSUE THREAD

**Issue by vera052020** [lucasmansilla/ACRN_Chest_X-ray_IA#3]
Dear Lucas:
     
      I want to ask you about how to deal with the remaining two data sets. If possible, I hope you can give me the processed data .

Looking forward to your reply.

**Comment by lucasmansilla** [comment]
Hello @vera052020,

Yes, of course. Please give me your email address or write to me so I can send you the preprocessed data in the next few days.

Regards.

**Comment by vera052020** [comment]
Thank you for your reply.

My email address is :1900432054@email.szu.edu.cn

Kind regards.
